# Generated by Django 5.0.1 on 2024-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
