# Generated by Django 5.0.1 on 2024-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_checkoutdb_remove_cartdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Orderstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='PaymentID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
