# Generated by Django 5.0.1 on 2024-02-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_checkoutdb_orderstatus_checkoutdb_paymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
