# Generated by Django 5.0.1 on 2024-03-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
